//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounters
    {
        public accounters()
        {
            this.expenses = new HashSet<expenses>();
            this.financialCustody = new HashSet<financialCustody>();
        }
    
        public int id { get; set; }
        public string fullname { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string socialCardNumber { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<expenses> expenses { get; set; }
        public virtual ICollection<financialCustody> financialCustody { get; set; }
    }
}
