//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cheques
    {
        public int id { get; set; }
        public Nullable<int> projectId { get; set; }
        public Nullable<double> chequeTotal { get; set; }
        public Nullable<double> taxes { get; set; }
        public Nullable<double> total { get; set; }
        public string chequeNumber { get; set; }
        public string bankName { get; set; }
        public string branch { get; set; }
        public Nullable<System.DateTime> chequeDate { get; set; }
        public string notes { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> companyId { get; set; }
    
        public virtual companies companies { get; set; }
        public virtual projects projects { get; set; }
    }
}
