//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class companies
    {
        public companies()
        {
            this.cheques = new HashSet<cheques>();
            this.projects = new HashSet<projects>();
        }
    
        public int id { get; set; }
        public string companyName { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<cheques> cheques { get; set; }
        public virtual ICollection<projects> projects { get; set; }
    }
}
