//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactsLoans
    {
        public contactsLoans()
        {
            this.loans = new HashSet<loans>();
            this.loansItems = new HashSet<loansItems>();
        }
    
        public int id { get; set; }
        public string contactName { get; set; }
        public string idNumber { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string address { get; set; }
    
        public virtual ICollection<loans> loans { get; set; }
        public virtual ICollection<loansItems> loansItems { get; set; }
    }
}
