//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class expenses
    {
        public int id { get; set; }
        public Nullable<int> projectId { get; set; }
        public Nullable<int> expenseTypeId { get; set; }
        public Nullable<double> quantity { get; set; }
        public Nullable<double> unitPrice { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<System.DateTime> expenseDate { get; set; }
        public string description { get; set; }
        public Nullable<int> accountantId { get; set; }
        public Nullable<bool> isSettlement { get; set; }
    
        public virtual accounters accounters { get; set; }
        public virtual expensesTypes expensesTypes { get; set; }
        public virtual projects projects { get; set; }
    }
}
