//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class expensesTypes
    {
        public expensesTypes()
        {
            this.expenses = new HashSet<expenses>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<expenses> expenses { get; set; }
    }
}
