//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public inventory()
        {
            this.inventoryProjectRelease = new HashSet<inventoryProjectRelease>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public string unit { get; set; }
        public Nullable<double> quantity { get; set; }
        public Nullable<double> unitPrice { get; set; }
        public Nullable<double> releasedQuantity { get; set; }
        public Nullable<double> remainingQauntity { get; set; }
    
        public virtual ICollection<inventoryProjectRelease> inventoryProjectRelease { get; set; }
    }
}
