//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class loansItems
    {
        public int id { get; set; }
        public Nullable<double> value { get; set; }
        public Nullable<System.DateTime> dueDate { get; set; }
        public Nullable<int> loanId { get; set; }
        public string byWho { get; set; }
        public string notes { get; set; }
        public Nullable<int> contactId { get; set; }
    
        public virtual loans loans { get; set; }
        public virtual contactsLoans contactsLoans { get; set; }
    }
}
