//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class projectItems
    {
        public projectItems()
        {
            this.invoicesItems = new HashSet<invoicesItems>();
        }
    
        public int id { get; set; }
        public Nullable<int> projectId { get; set; }
        public Nullable<int> arrange { get; set; }
        public string description { get; set; }
        public string unit { get; set; }
        public Nullable<double> unitPrice { get; set; }
    
        public virtual ICollection<invoicesItems> invoicesItems { get; set; }
        public virtual projects projects { get; set; }
    }
}
