//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class projects
    {
        public projects()
        {
            this.cheques = new HashSet<cheques>();
            this.expenses = new HashSet<expenses>();
            this.financialCustody = new HashSet<financialCustody>();
            this.inventoryProjectRelease = new HashSet<inventoryProjectRelease>();
            this.invoices = new HashSet<invoices>();
            this.projectItems = new HashSet<projectItems>();
            this.projectsContacts = new HashSet<projectsContacts>();
            this.projectsSubContractors = new HashSet<projectsSubContractors>();
            this.projectsWorkers = new HashSet<projectsWorkers>();
            this.subContractorsCustody = new HashSet<subContractorsCustody>();
            this.subContractorsItems = new HashSet<subContractorsItems>();
            this.workerTimeSheet = new HashSet<workerTimeSheet>();
        }
    
        public int id { get; set; }
        public Nullable<int> companyId { get; set; }
        public string projectName { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> finishDate { get; set; }
        public Nullable<int> accountantId { get; set; }
    
        public virtual ICollection<cheques> cheques { get; set; }
        public virtual companies companies { get; set; }
        public virtual ICollection<expenses> expenses { get; set; }
        public virtual ICollection<financialCustody> financialCustody { get; set; }
        public virtual ICollection<inventoryProjectRelease> inventoryProjectRelease { get; set; }
        public virtual ICollection<invoices> invoices { get; set; }
        public virtual ICollection<projectItems> projectItems { get; set; }
        public virtual ICollection<projectsContacts> projectsContacts { get; set; }
        public virtual ICollection<projectsSubContractors> projectsSubContractors { get; set; }
        public virtual ICollection<projectsWorkers> projectsWorkers { get; set; }
        public virtual ICollection<subContractorsCustody> subContractorsCustody { get; set; }
        public virtual ICollection<subContractorsItems> subContractorsItems { get; set; }
        public virtual ICollection<workerTimeSheet> workerTimeSheet { get; set; }
    }
}
