//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class workerLoans
    {
        public int id { get; set; }
        public Nullable<int> workerId { get; set; }
        public Nullable<System.DateTime> workDate { get; set; }
        public Nullable<double> total { get; set; }
        public string notes { get; set; }
        public Nullable<int> projectId { get; set; }
    
        public virtual workers workers { get; set; }
    }
}
