//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class workerTypes
    {
        public workerTypes()
        {
            this.workers = new HashSet<workers>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
    
        public virtual ICollection<workers> workers { get; set; }
    }
}
