//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class workers
    {
        public workers()
        {
            this.projectsWorkers = new HashSet<projectsWorkers>();
            this.workerLoans = new HashSet<workerLoans>();
            this.workerTimeSheet = new HashSet<workerTimeSheet>();
        }
    
        public int id { get; set; }
        public string fullname { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string socialCardNumber { get; set; }
        public Nullable<double> daySalary { get; set; }
        public Nullable<int> workerTypeId { get; set; }
    
        public virtual ICollection<projectsWorkers> projectsWorkers { get; set; }
        public virtual ICollection<workerLoans> workerLoans { get; set; }
        public virtual workerTypes workerTypes { get; set; }
        public virtual ICollection<workerTimeSheet> workerTimeSheet { get; set; }
    }
}
